"""empty message

Revision ID: 12442bde4f2b
Revises: 6e2a933b113f
Create Date: 2022-08-03 15:44:11.737763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12442bde4f2b'
down_revision = '6e2a933b113f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('talent_seeking_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'talent_seeking_message')
    op.drop_column('Venue', 'seeking_talent')
    op.drop_table('Genres')
    # ### end Alembic commands ###
