"""empty message

Revision ID: 429f9afa248f
Revises: ac0940f0df03
Create Date: 2022-08-03 15:52:36.116681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '429f9afa248f'
down_revision = 'ac0940f0df03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.String(length=120), nullable=True))
    op.drop_constraint('Venue_genres_id_fkey', 'Venue', type_='foreignkey')
    op.drop_column('Venue', 'genres_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Venue_genres_id_fkey', 'Venue', 'Genres', ['genres_id'], ['id'])
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###
