"""empty message

Revision ID: 478f7a8b6cf4
Revises: 7bc2e0beaea3
Create Date: 2022-08-04 20:41:10.961255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '478f7a8b6cf4'
down_revision = '7bc2e0beaea3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website', sa.String(length=250), nullable=True))
    op.add_column('Artist', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('seeking_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'seeking_description')
    op.drop_column('Artist', 'seeking_talent')
    op.drop_column('Artist', 'website')
    # ### end Alembic commands ###
