"""empty message

Revision ID: 751fdd08c04e
Revises: ba8aaaff9d7a
Create Date: 2022-08-04 20:31:08.667415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '751fdd08c04e'
down_revision = 'ba8aaaff9d7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('seeking_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeking_description')
    op.drop_column('Venue', 'seeking_talent')
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###
